apiVersion: v1
kind: Namespace
metadata:
  name: QA-deployment
  labels:
    apps: web-based
  annotations:
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: QA-deployment
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore
  labels:
    app: Prod
  namespace: QA-deployment
  annotations:
    monitoring: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Prod
  template:
    metadata:
      labels:
        app: Prod
    spec:
      containers:
      - image: steju480/bookstore.app.v1:latest
        name: bookstore
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: Prod
  name: prod-service
  namespace: QA-deployment
spec:
  ports:
  - nodePort: 30003
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: Prod
  type: NodePort
